# Generated by Django 4.1 on 2022-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.BigIntegerField(unique=True),
        ),
    ]
