# Generated by Django 4.1 on 2022-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
