# Generated by Django 4.1 on 2022-11-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_product_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='index',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
