# Generated by Django 4.1 on 2023-02-04 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_cart_cart_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 10, 53, 45, 450970)),
        ),
    ]
