# Generated by Django 4.1 on 2023-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_cart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
